SCREEN_WIDTH = 1280 *2
SCREEN_HEIGHT = 720 *2

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 #seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 50
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 225