SCREEN_WIDTH = 1280 *2
SCREEN_HEIGHT = 720 *2

ASTEROID_MIN_RADIUS = 15
ASTEROID_KINDS = 5
ASTEROID_SPAWN_RATE = 0.8 #seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ACCEL_FACTOR = 1.2

PLAYER_RADIUS = 90
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 225
SHOT_RADIUS = 15
PLAYER_SHOOT_SPEED = 700
PLAYER_SHOT_COOLDOWN = 0.2

FRAME_DURATION = 100